### ISSUE TITLE
Некорректная генерация Sec-Vtrans-Token

### ISSUE THREAD

**Issue by thedanill** [FOSWLY/vot.js#36]
Токен состоит из четырёх элементов: `${sign}:${uuid}:${path}:${version}`. 
Последние три части генерируются корректно, а вот с подписью есть проблема — вместо подписи токена используется подпись запроса:
```
const sign = await getSignature(body);
<..>
"Sec-Vtrans-Token": `${sign}:${uuid}:${this.paths.videoTranslationAudio}:${this.componentVersion}`
```
На самом деле, подпись токена — это HMAC-SHA256 с ключом `config.hmac`, но от строки `'${uuid}:${this.paths.videoTranslationAudio}:${this.componentVersion}'`.

Сейчас она не проверяется сервером, но это может измениться в ближайшем будущем.

**Comment by ilyhalight** [comment]
Исправил недоработку
